### PR TITLE
Bump build number for retrigger

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
error:
```
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/conda/feedstock_root/build_artifacts/r-multipanelfigure_1561832106447/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/R/library/magick/libs/magick.so':
  libgfortran.so.3: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘multipanelfigure’
```

Looks like an unusual error for a norach build. ... Either this is not noarch or some transitive dependency is missing. Any other idea?

**Comment by dpryan79** [comment]
I bet that's coming from the r-magick dependency.

**Comment by dbast** [comment]
Interesting... the old r-magick CI test env had `libgfortran:           3.0.0-1                  conda-forge` installed. The CI Test env of this build has `libgfortran-ng:         7.3.0-hdf63c60_0              defaults` installed... Is this a pinning issue?... Maybe a new r-magick rebuild with current pinning helps?

**Comment by dpryan79** [comment]
> Maybe a new r-magick rebuild with current pinning helps?

Yeah, looks like it was never updated for the newer compilers: https://github.com/conda-forge/r-magick-feedstock/pull/2

**Comment by dbast** [comment]
Ah. Me then wonders why conda even was able to install it in this build here.

**Pull request merged**
